name: Test
on:
  push:
    branches: [master]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5'

      - name: Install bundler
        run: gem install bundler -v '2.1.4'

      - name: Install dependencies
        run: bundle install --without staging

      - name: Test
        run: bundle exec rspec --exclude-pattern "**/integration/**/*_spec.rb, **/e2e/**/*_spec.rb"
